package ui;


import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import jmr.descriptor.Comparator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laura
 */
public class ComparatorRender extends javax.swing.JPanel implements ListCellRenderer<Comparator>{
    private static final ComparatorRender INSTANCE=new ComparatorRender();
    /**
     * Creates new form ComparatorRender
     */
    private ComparatorRender() {
        initComponents();
    }
    
    public static ComparatorRender getInstance(){return INSTANCE;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(60, 35));
        setPreferredSize(new java.awt.Dimension(60, 35));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Comparator");
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 18));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 18));
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public Component getListCellRendererComponent(JList<? extends Comparator> jlist, Comparator e, int i, boolean bln, boolean bln1) {
        this.jLabel1.setText(e.getClass().getSimpleName());
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
