/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author laura
 */
public class TypeComparatorRender extends javax.swing.JPanel implements ListCellRenderer<Integer> {
    private static final TypeComparatorRender INSTANCE=new TypeComparatorRender();
    
    /**
     * Creates new form TypeComparatorRender
     */
    private TypeComparatorRender() {
        initComponents();
    }
    
    public static TypeComparatorRender getInstance(){return INSTANCE;}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(73, 35));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Prueba");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 18));
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 30));
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public String getLabel(){
        return this.jLabel1.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Integer> jlist, Integer e, int i, boolean bln, boolean bln1) {
        switch(e){
            case 1:
                this.jLabel1.setText("Máximo");
                break;
            case 2:
                this.jLabel1.setText("Mínimo");
                break;
            case 3:
                this.jLabel1.setText("Media");
                break;
            case 4:
            default:
                this.jLabel1.setText("Euclídea");
        }
        return this;
    }
}
